### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'toUpperCase')

### ISSUE THREAD

**Issue by korolevsv** [Chia-Network/chia-blockchain-gui#1065]
### What happened?

GUI stuck while plotting Bladebit. Temp directory -342 GB on disk, 3080 files. Free space on disk only 2 GB left. No changes after 10 hours.
Error occured when switched several times between different GUI tabs (Pols-Wallet-Full Node)

### Version

1.6.1b3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'toUpperCase')

URL
#/dashboard/wallets/7

Stacktrace
at webpack://@chia/wallets/dist/esm.js:800:67 labels
at webpack://@chia/gui/node_modules/victory-core/es/victory-util/helpers.js:169:29 evaluateProp
at webpack://@chia/gui/node_modules/victory-tooltip/es/victory-tooltip.js:136:17 value
at webpack://@chia/gui/node_modules/victory-tooltip/es/victory-tooltip.js:492:32 Helpers.evaluateProp
at webpack://@chia/gui/node_modules/victory-tooltip/es/victory-tooltip.js:508:18 value
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:187:187 qi
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:186:172 pi
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:426 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
```

**Comment by paninaro** [comment]
Fix has been included in 1.6.1
