### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by necessities** [Chia-Network/chia-blockchain-gui#1220]
### What happened?

Clicked on NFT in wallet. Node and wallet were still syncing. 

### Version

1.7.0b3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'length')

URL
#/dashboard/nfts/nft10pgxd0emyyz3avy0sgyxl2tp7fhy4w59at2fljfzll5hvcz30hvsal4thg

Stacktrace
at webpack://@chia/gui/node_modules/bech32/dist/index.js:84:19 encode
at webpack://@chia/src/utils/toBech32m.ts:25:9 value.startsWith
at webpack://@chia/gui/src/components/nfts/NFTDetails.tsx:83:24 toBech32m
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:172:114 useLayoutEffect
at webpack://@chia/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia/gui/src/components/nfts/NFTDetails.tsx:45:18 NFTDetails
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:267:459 b?b.sibling:null}I
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
```

**Comment by seeden** [comment]
Thank you for bug report @necessities. It will be fixed in next release via https://github.com/Chia-Network/chia-blockchain-gui/pull/1226
