### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'pk')

### ISSUE THREAD

**Issue by WAWAN19831** [Chia-Network/chia-blockchain-gui#1295]
### What happened?

седьмого января создал кошелёк для монет того же дня послал для проверке 0.2 монеты кошелёк какой уже день не отоброжает монеты и не синхронизируетс я удалил  переустановил заного ошибка что делать не знаю а в сканере показывает что монеты на кошельке а по факту кашелёк не работает а щас вот что происходит 

кошелёк 1818749105

шибка: Cannot read properties of undefined (reading 'pk')
at webpack://@chia-network/src/screens/SelectKey/SelectKeyDetailDialog.tsx:85:26 pk
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:342 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia-network/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next

### Version

скрин     https://prnt.sc/D8Pt5CieAo3K

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'pk')

URL
#/

Stacktrace
at webpack://@chia-network/src/screens/SelectKey/SelectKeyDetailDialog.tsx:85:26 pk
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:342 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia-network/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
```

**Comment by WAWAN19831** [comment]
удалил ключи вошёл заново по мнемонической фразе вот что показывает   https://prnt.sc/pzSx65wR4Ykt
