### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by xahmedxsa55** [Chia-Network/chia-blockchain-gui#1313]
### What happened?

?

### Version

Version 1.6.2 | 64 bit

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'map')

URL
#/dashboard/offers/manage

Stacktrace
at webpack://@chia-network/gui/src/hooks/useAssetIdName.ts:28:12 useAssetIdName
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:168:376 $h
at webpack://@chia-network/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia-network/gui/src/hooks/useAssetIdName.ts:20:54 useAssetIdName
at webpack://@chia-network/gui/src/hooks/useSaveOfferFile.ts:14:30 useSaveOfferFile
at webpack://@chia-network/gui/src/components/offers/OfferManager.tsx:509:22 CreateOffer
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:342 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
```

**Comment by MumfMeisterT** [comment]
This is fixed in the next release.
