### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by zavadichr** [Chia-Network/chia-blockchain-gui#1686]
### What happened?

Crashed when I tried to create offer. Sync is ok

### Version

1.8.0rc-1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'trim')

URL
#/dashboard/offers/builder

Stacktrace
at webpack://@chia-network/gui/src/util/getNFTId.ts:6:25 getNFTId
at webpack://@chia-network/gui/src/components/nfts/NFTCard.tsx:35:30 NFTCard
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:172:114 useLayoutEffect
at webpack://@chia-network/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia-network/gui/src/components/nfts/NFTCard.tsx:35:16 NFTCard
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:178:168 ki
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:177:177 ii
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:274:125 k.firstContext;null!==l;){if(l.context===d&&0!==(l.observedBits&f)){1===h.tag&&(l=zg(-1,c&-c),l.tag=2,Ag(h,l));h.lanes|=c;l=h.alternate;null!==l&&(l.lanes|=c);sg
```

**Comment by paninaro** [comment]
Thanks for the report. This is fixed by https://github.com/Chia-Network/chia-blockchain-gui/pull/1704
