### ISSUE TITLE
[BUG] Can't create NFT offers.

### ISSUE THREAD

**Issue by codephunk** [Chia-Network/chia-blockchain-gui#1714]
### What happened?

In the latest 1.8.0-rc1 I can not create offers for any of my NFTs. Whenever I click on "Create Offer" in the context menu for an NFT, I get a "Something went wrong" error. After that happens I have to reload the app to continue.

### Version

1.8.0-rc3

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'trim')

URL
#/dashboard/offers/builder

Stacktrace
at webpack://@chia-network/gui/src/util/getNFTId.ts:6:25 getNFTId
at webpack://@chia-network/gui/src/components/nfts/NFTCard.tsx:35:30 NFTCard
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:172:114 useLayoutEffect
at webpack://@chia-network/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia-network/gui/src/components/nfts/NFTCard.tsx:35:16 NFTCard
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:178:168 ki
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:177:177 ii
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:274:125 k.firstContext;null!==l;){if(l.context===d&&0!==(l.observedBits&f)){1===h.tag&&(l=zg(-1,c&-c),l.tag=2,Ag(h,l));h.lanes|=c;l=h.alternate;null!==l&&(l.lanes|=c);sg
```

**Comment by esaung** [comment]
Thanks @codephunk - please try RC3 build, the offer creation issue is fixed with that version.
