### ISSUE TITLE
[Bug] dictionary changed size during iteration 

### ISSUE THREAD

**Issue by bramv-chia** [Chia-Network/chia-blockchain-gui#1719]
### What happened?

when switching between wallets 
![wallet_change_error_GUI](https://user-images.githubusercontent.com/116583441/234676534-8ff77ef9-f1ac-4301-b134-2b52bcc1a437.png)
occured.
after clicking [OK] and clicking on the desired wallet, it will load without issue

### Version

1.8.0rc3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Interestingly, this is actually a python error message. @bramv-chia any chance you can find that error message in your debug log?

**Comment by bramv-chia** [comment]
@paninaro 
2023-04-26T07:06:48.114 wallet chia.wallet.wallet_node    : INFO     Sync (trusted: True) duration was: 51.454047441482544
2023-04-26T07:06:48.148 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 317, in log_in
  File "chia\wallet\wallet_node.py", line 388, in _start_with_fingerprint
RuntimeError: dictionary changed size during iteration

**Comment by paninaro** [comment]
Thanks @bramv-chia I'll transfer this to the blockchain repo and assign it.
