### ISSUE TITLE
[Bug] Cancel Offer in GUI does not work

### ISSUE THREAD

**Issue by XCHSystems** [Chia-Network/chia-blockchain-gui#1763]
### What happened?

Attempted to cancel an offer in the GUI, selected the NFT and chose "Cancel Offer", proceeded to select the blockchain fee, however the offer never gets cancelled, tried both 1.7.0 and 1.8.0 of the client, this is what I see in the log:

`2023-05-11T13:37:10.344 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1696, in cancel_offer
  File "chia\wallet\trade_manager.py", line 257, in cancel_pending_offer_safely
  File "chia\wallet\nft_wallet\nft_wallet.py", line 644, in generate_signed_transaction
  File "chia\wallet\nft_wallet\nft_wallet.py", line 710, in generate_unsigned_spendbundle
AssertionError

2023-05-11T13:37:10.352 daemon __main__                   : DEBUG    Received message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"ack": true, "command": "cancel_offer", "data": {"error": "", "success": false}, "destination": "wallet_ui", "origin": "chia_wallet", "request_id": `

### Version

1.8.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
2023-05-11T13:37:10.344 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1696, in cancel_offer
  File "chia\wallet\trade_manager.py", line 257, in cancel_pending_offer_safely
  File "chia\wallet\nft_wallet\nft_wallet.py", line 644, in generate_signed_transaction
  File "chia\wallet\nft_wallet\nft_wallet.py", line 710, in generate_unsigned_spendbundle
AssertionError

2023-05-11T13:37:10.352 daemon __main__                   : DEBUG    Received message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"ack": true, "command": "cancel_offer", "data": {"error": "", "success": false}, "destination": "wallet_ui", "origin": "chia_wallet", "request_id":
```

**Comment by paninaro** [comment]
This happens when the NFT coin can't be found. Seems likely that the NFT has been spent to a new coin by transfer/DID-assignment/metadata-update. Are you able to share the offer data?

**Comment by XCHSystems** [comment]
> This happens when the NFT coin can't be found. Seems likely that the NFT has been spent to a new coin by transfer/DID-assignment/metadata-update. Are you able to share the offer data?

Unfortunately not, as part of the troubleshooting process, I deleted the config.yaml, and walled DB file and performed a resync, now all my "Offers" have disappeared, and some of my NFT's now showing as "Invalid Hash".  Also my farmer wallet only shows 50x NFTs in one Profile Wallet, whereas the UI shows the correct amount of 100.
