### ISSUE TITLE
[BUG] Fingerprint is not defined

### ISSUE THREAD

**Issue by YusakuMuroya** [Chia-Network/chia-blockchain-gui#1814]
### What happened?

v1.8.2 rc1 did not start correctly on windows 11.

### Version

1.8.2-rc1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Fingerprint is not defined

URL
#/

Stacktrace
at webpack://@chia-network/src/hooks/useFingerprintSettings.ts:16:14 useFingerprintSettings<Type extends Serializable>
at webpack://@chia-network/gui/src/components/notification/NotificationsProvider.tsx:121:4 setLastPushNotificationTimestamp
at webpack://@chia-network/gui/src/components/notification/NotificationsProvider.tsx:184:4 showPushNotifications
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:262:358 fk
at webpack://@chia-network/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:122:324 eg
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:261:307 ek
at webpack://@chia-network/gui/node_modules/react-dom/cjs/react-dom.production.min.js:261:214 ek
at webpack://@chia-network/gui/node_modules/scheduler/cjs/scheduler.production.min.js:16:223 V
at webpack://@chia-network/gui/node_modules/scheduler/cjs/scheduler.production.min.js:12:345 k
```

**Comment by Ganbin** [comment]
Got the same on Mac OS `12.6.2` arm.

**Comment by YusakuMuroya** [comment]
> Got the same on Mac OS `12.6.2` arm.

In my case, this problem was not occurred in v1.8.2 rc2.
Please try it.
