### ISSUE TITLE
Wallet temporarily shows old clawback tx while syncing [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain-gui#1864]
### What happened?

This was logged immediately after [issue 1863](https://github.com/Chia-Network/chia-blockchain-gui/issues/1863). The state of the wallet was such that several clawback transactions had been sent to it, but none had been accepted because it has zero XCH.

Previous attempts to claim clawbacks disappear and reappear while the wallet is syncing.

https://github.com/Chia-Network/chia-blockchain-gui/assets/69756004/88405707-1f41-4eac-880b-3a53aead253c

### Version

1.8.2rc4 + PR 15496

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
2023-06-21T14:07:27.070 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'BAD_AGGREGATE_SIGNATURE',
 'status': 3,
 'txid': '0x279ed5e862f6c0c08f2f60e1ac12670b51bec712f6fb4a924c4d895ee19902b2'}
2023-06-21T14:07:27.121 wallet chia.wallet.wallet         : WARNING  Can't select amount higher than our spendable balance.  Amount: 100000000, spendable: 0
2023-06-21T14:07:27.122 wallet chia.wallet.wallet_node    : ERROR    Exception handling NewPeakItem(item_type=<NewPeakQueueTypes.NEW_PEAK_WALLET: 4>, data=(NewPeakWallet(header_hash=<bytes32: 11e8f5634e19141aeeffd0a77e7a071518b81ff91a25e9b349682f2db53ad7c0>, height=2805039, weight=170754176718, fork_point_with_previous_peak=2805039), WSChiaConnection(local_type=<NodeType.WALLET: 6>, local_port=8449, local_capabilities=[<Capability.BASE: 1>, <Capability.BLOCK_HEADERS: 2>, <Capability.RATE_LIMITS_V2: 3>], peer_info=PeerInfo(_ip=IPv4Address('127.0.0.1'), _port=58444), peer_node_id=<bytes32: b3d9de85d29931c10050b56c7afb91c99141943fc81ff2d1a8425e52be0d08ab>, outbound_rate_limiter=<chia.server.rate_limits.RateLimiter object at 0x000001D378427400>, inbound_rate_limiter=<chia.server.rate_limits.RateLimiter object at 0x000001D3784B9F70>, is_outbound=True, creation_time=1687374445.0260527, bytes_read=92875, bytes_written=62425, last_message_time=1687374447.0093956, peer_server_port=58444, active=False, closed=False, connection_type=<NodeType.FULL_NODE: 1>, request_nonce=26, peer_capabilities=[<Capability.BASE: 1>, <Capability.BLOCK_HEADERS: 2>, <Capability.RATE_LIMITS_V2: 3>], version=<Version('1.8.2rc4')>, protocol_version=<Version('0.0.34')>))), Can't select amount higher than our spendable balance.  Amount: 100000000, spendable: 0 Traceback (most recent call last):
  File "C:\Users\User\Chia\1.8.2\chia-blockchain\chia\wallet\wallet_node.py", line 593, in _process_new_subscriptions
    await self.wallet_state_manager.auto_claim_coins()
  File "C:\Users\User\Chia\1.8.2\chia-blockchain\chia\wallet\wallet_state_manager.py", line 725, in auto_claim_coins
    await self.spend_clawback_coins(clawback_coins, tx_fee)
  File "C:\Users\User\Chia\1.8.2\chia-blockchain\chia\wallet\wallet_state_manager.py", line 778, in spend_clawback_coins
    chia_tx = await self.main_wallet.create_tandem_xch_tx(
  File "C:\Users\User\Chia\1.8.2\chia-blockchain\chia\wallet\wallet.py", line 586, in create_tandem_xch_tx
    chia_coins = await self.select_coins(fee)
  File "C:\Users\User\Chia\1.8.2\chia-blockchain\chia\wallet\wallet.py", line 292, in select_coins
    coins = await select_coins(
  File "C:\Users\User\Chia\1.8.2\chia-blockchain\chia\wallet\coin_selection.py", line 39, in select_coins
    raise ValueError(error_msg)
ValueError: Can't select amount higher than our spendable balance.  Amount: 100000000, spendable: 0

2023-06-21T14:07:27.124 wallet wallet_server              : WARNING  Trying to ban localhost for 9999, but will not ban
2023-06-21T14:07:28.257 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction d16da4ec4f37b53984b4479d7bb45c79457e6e4d621968efad8db934e907c9bf: Cannot find coin record for clawback transaction 0xd16da4ec4f37b53984b4479d7bb45c79457e6e4d621968efad8db934e907c9bf
2023-06-21T14:07:28.259 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction 542d61deadb2252eb88bb3ccc088a6488b58705daae34145593ce630d266004a: Cannot find coin record for clawback transaction 0x542d61deadb2252eb88bb3ccc088a6488b58705daae34145593ce630d266004a
2023-06-21T14:07:28.261 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction e3db05afb0a67eb1dcc5206ec71fb95214f052f255aca45f039ee6ebd71cbd6c: Cannot find coin record for clawback transaction 0xe3db05afb0a67eb1dcc5206ec71fb95214f052f255aca45f039ee6ebd71cbd6c
2023-06-21T14:07:28.307 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction d16da4ec4f37b53984b4479d7bb45c79457e6e4d621968efad8db934e907c9bf: Cannot find coin record for clawback transaction 0xd16da4ec4f37b53984b4479d7bb45c79457e6e4d621968efad8db934e907c9bf
2023-06-21T14:07:28.309 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction 542d61deadb2252eb88bb3ccc088a6488b58705daae34145593ce630d266004a: Cannot find coin record for clawback transaction 0x542d61deadb2252eb88bb3ccc088a6488b58705daae34145593ce630d266004a
2023-06-21T14:07:28.310 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction e3db05afb0a67eb1dcc5206ec71fb95214f052f255aca45f039ee6ebd71cbd6c: Cannot find coin record for clawback transaction 0xe3db05afb0a67eb1dcc5206ec71fb95214f052f255aca45f039ee6ebd71cbd6c
2023-06-21T14:07:28.897 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction d16da4ec4f37b53984b4479d7bb45c79457e6e4d621968efad8db934e907c9bf: Cannot find coin record for clawback transaction 0xd16da4ec4f37b53984b4479d7bb45c79457e6e4d621968efad8db934e907c9bf
2023-06-21T14:07:28.899 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction 542d61deadb2252eb88bb3ccc088a6488b58705daae34145593ce630d266004a: Cannot find coin record for clawback transaction 0x542d61deadb2252eb88bb3ccc088a6488b58705daae34145593ce630d266004a
2023-06-21T14:07:28.900 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction e3db05afb0a67eb1dcc5206ec71fb95214f052f255aca45f039ee6ebd71cbd6c: Cannot find coin record for clawback transaction 0xe3db05afb0a67eb1dcc5206ec71fb95214f052f255aca45f039ee6ebd71cbd6c
2023-06-21T14:07:28.902 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction d16da4ec4f37b53984b4479d7bb45c79457e6e4d621968efad8db934e907c9bf: Cannot find coin record for clawback transaction 0xd16da4ec4f37b53984b4479d7bb45c79457e6e4d621968efad8db934e907c9bf
2023-06-21T14:07:28.903 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction 542d61deadb2252eb88bb3ccc088a6488b58705daae34145593ce630d266004a: Cannot find coin record for clawback transaction 0x542d61deadb2252eb88bb3ccc088a6488b58705daae34145593ce630d266004a
2023-06-21T14:07:28.905 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction e3db05afb0a67eb1dcc5206ec71fb95214f052f255aca45f039ee6ebd71cbd6c: Cannot find coin record for clawback transaction 0xe3db05afb0a67eb1dcc5206ec71fb95214f052f255aca45f039ee6ebd71cbd6c
2023-06-21T14:07:29.347 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction d16da4ec4f37b53984b4479d7bb45c79457e6e4d621968efad8db934e907c9bf: Cannot find coin record for clawback transaction 0xd16da4ec4f37b53984b4479d7bb45c79457e6e4d621968efad8db934e907c9bf
2023-06-21T14:07:29.349 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction 542d61deadb2252eb88bb3ccc088a6488b58705daae34145593ce630d266004a: Cannot find coin record for clawback transaction 0x542d61deadb2252eb88bb3ccc088a6488b58705daae34145593ce630d266004a
2023-06-21T14:07:29.352 wallet chia.rpc.wallet_rpc_api    : ERROR    Failed to get transaction e3db05afb0a67eb1dcc5206ec71fb95214f052f255aca45f039ee6ebd71cbd6c: Cannot find coin record for clawback transaction 0xe3db05afb0a67eb1dcc5206ec71fb95214f052f255aca45f039ee6ebd71cbd6c
2023-06-21T14:07:29.412 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'BAD_AGGREGATE_SIGNATURE',
 'status': 3,
 'txid': '0xa56633d13671cdd0f6ca79a80fa5c66aa76064ab4fd3c1f201bddfc6be4a2211'}
```

**Comment by danieljperry** [comment]
Ten minutes later and the same behavior is still happening. The wallet has not synced and might be borked. This wallet had only a few clawback transactions in its history and was running in trusted mode.

**Comment by danieljperry** [comment]
OK it eventually synced and the unfinished clawback transactions have disappeared. All looks normal again.

**Comment by danieljperry** [comment]
Update: the wallet does eventually sync.

**Comment by paninaro** [comment]
RC5 will display an alert if you try to claim while the wallet is still syncing: https://github.com/Chia-Network/chia-blockchain-gui/issues/1864

**Comment by paninaro** [comment]
@zsolt-dev I'm not sure if you had other plans for going further to address this. I think the alert is sufficient.

**Comment by danieljperry** [comment]
This video shows a related issue. When loading the sender's wallet, an old clawback transaction is erroneously shown:
- the wallet claims to be synced
- the same transaction is shown 3 times
- with each "accept", the old transaction instantly disappears and no balances change
- **the derivation index increases** with each "accept", which appears to indicate that the wallet wasn't actually synced

https://github.com/Chia-Network/chia-blockchain-gui/assets/69756004/0a68913d-9ade-4fd1-9795-1124551929ea

**Comment by paninaro** [comment]
@danieljperry Can you take a look with the latest 2.0.0 beta to see if your concerns have been addressed? Maybe a further remediation would be to hide the clawback section until syncing is complete.

**Comment by danieljperry** [comment]
> @danieljperry Can you take a look with the latest 2.0.0 beta to see if your concerns have been addressed? Maybe a further remediation would be to hide the clawback section until syncing is complete.

I'm running 2.0.0b5 now. I think the GUI has improved, but this issue still exists. In the following video, I already clawed back the coin from the "Clawback Sender" wallet. There are still two issues, the first of which is minor:
1. While syncing the "Clawback Recipient" wallet, the clawback appears and disappears. My opinion is that the wallet shouldn't show any balances while it is syncing, but at least the final state is correct, so I don't think this is a big deal.
2. While syncing the "Clawback Sender" wallet, the "Clawback" button is shown, but this transaction has already been clawed back. It's not shown three times like it was previously, but it is still there. The final balance is correct, but I need to attempt the clawback in order to get the wallet to sync completely.


https://github.com/Chia-Network/chia-blockchain-gui/assets/69756004/6bfaffea-7e66-4a4e-bb72-7efceb8b0146
