### ISSUE TITLE
[BUG] Invalid attempt to destructure non-iterable instance.In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

### ISSUE THREAD

**Issue by Kruger1981** [Chia-Network/chia-blockchain-gui#2030]
### What happened?

error when clicking harvester option

### Version

2.0.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

URL
#/dashboard/harvest

Stacktrace
at webpack://node_modules/@babel/runtime/helpers/nonIterableRest.js:2:8 _nonIterableRest
at webpack://node_modules/@babel/runtime/helpers/slicedToArray.js:10:102 _slicedToArray
at webpack://@chia-network/src/components/FormatBytes/FormatBytes.tsx:54:34 CovertReversed
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:267:459 b?b.sibling:null}I
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
```

**Comment by paninaro** [comment]
@ChiaMineJP does this report have enough info to investigate?
