### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by netserver** [Chia-Network/chia-blockchain-gui#2253]
### What happened?

click in farm icon of gui crash gui

### Version

2.1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'length')

URL
#/dashboard/plot

Stacktrace
at webpack://@chia-network/gui/src/components/plot/overview/PlotOverviewPlots.tsx:51:44 length
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:167:136 Xh
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:197:257 hj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:292:87 null,Zf(d)?(f=!0,cg
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:388 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:319 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:280:179 uj
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:271:87 Ok
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:273:299 Dk
at webpack://node_modules/react-dom/cjs/react-dom.production.min.js:127:104 jg
```

**Comment by emlowe** [comment]
Fixed in 2.2.0
