### ISSUE TITLE
[1.0.4] install-gui.sh fails on Raspberry Pi 4: undefined reference to `png_init_filter_functions_neon'

### ISSUE THREAD

**Issue by Nitrooo** [Chia-Network/chia-blockchain-gui#252]
Installation of the GUI version 1.0.4 fails on my Pi4 running Manjaro Linux. Previous versions installed fine. It looks related to some NEON optimization in the `optipng` dependency.

Here's the relevant part of the npm log:

```
2464 verbose stack Error: command failed
2464 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
2464 verbose stack     at ChildProcess.emit (node:events:369:20)
2464 verbose stack     at maybeClose (node:internal/child_process:1067:16)
2464 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
2465 verbose pkgid optipng-bin@7.0.0
2466 verbose cwd /home/user/chia-blockchain/chia-blockchain-gui
2467 verbose Linux 5.10.25-3-MANJARO-ARM
2468 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
2469 verbose node v15.13.0
2470 verbose npm  v7.8.0
2471 error code 1
2472 error path /home/user/chia-blockchain/chia-blockchain-gui/node_modules/optipng-bin
2473 error command failed
2474 error command sh -c node lib/install.js
2475 error ⚠ Command failed: /home/user/chia-blockchain/chia-blockchain-gui/node_modules/optipng-bin/vendor/optipng --version
2475 error /home/user/chia-blockchain/chia-blockchain-gui/node_modules/optipng-bin/vendor/optipng: /home/user/chia-blockchain/chia-blockchain-gui/node_modules/optipng-bin/vendor/optipng: cannot execute binary file
2475 error
2475 error
2475 error   ⚠ optipng pre-build test failed
2475 error   ℹ compiling from source
2475 error   ✖ Error: Command failed: /bin/sh -c make install
2475 error pngrtran.c:99:1: warning: ‘png_rtran_ok’ defined but not used [-Wunused-function]
2475 error    99 | png_rtran_ok(png_structrp png_ptr, int need_IHDR)
2475 error       | ^~~~~~~~~~~~
2475 error ar: `u' modifier ignored since `D' is the default (see `U')
2475 error ar: `u' modifier ignored since `D' is the default (see `U')
2475 error ar: `u' modifier ignored since `D' is the default (see `U')
2475 error ar: `u' modifier ignored since `D' is the default (see `U')
2475 error pngxmem.c: In function ‘pngx_malloc_rows_extended’:
2475 error pngxmem.c:38:34: warning: comparison is always false due to limited range of data type [-Wtype-limits]
2475 error    38 |        (pngx_alloc_size_t)height > (pngx_alloc_size_t)(-1) / sizeof(png_bytep))
2475 error       |                                  ^
2475 error ar: `u' modifier ignored since `D' is the default (see `U')
2475 error /usr/bin/ld: ../libpng/libpng.a(pngrutil.o): in function `png_read_filter_row':
2475 error pngrutil.c:(.text+0x2284): undefined reference to `png_init_filter_functions_neon'
2475 error collect2: error: ld returned 1 exit status
2475 error make[1]: *** [Makefile:100: optipng] Error 1
2475 error make: *** [Makefile:14: install] Error 2
2475 error
2475 error cd src/optipng && \
2475 error make install && \
2475 error cd ../..
2475 error make[1]: Entering directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/optipng'
2475 error cd ../libpng && \
2475 error make -f Makefile PNGLIBCONF_H_PREBUILT=pnglibconf.h.optipng && \
2475 error cd ../optipng
2475 error make[2]: Entering directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/libpng'
2475 error cp pnglibconf.h.optipng pnglibconf.h
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o png.o png.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngerror.o pngerror.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngget.o pngget.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngmem.o pngmem.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngpread.o pngpread.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngread.o pngread.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngrio.o pngrio.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngrtran.o pngrtran.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngrutil.o pngrutil.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngset.o pngset.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngtrans.o pngtrans.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwio.o pngwio.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwrite.o pngwrite.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwtran.o pngwtran.c
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwutil.o pngwutil.c
2475 error ar rcs libpng.a png.o pngerror.o pngget.o pngmem.o pngpread.o pngread.o pngrio.o pngrtran.o pngrutil.o pngset.o pngtrans.o pngwio.o pngwrite.o pngwtran.o pngwutil.o
2475 error ranlib libpng.a
2475 error gcc -c -I../zlib  -O2 -Wall -Wextra -o pngtest.o pngtest.c
2475 error gcc  -L../zlib -o pngtest pngtest.o libpng.a -lz -lm
2475 error make[2]: Leaving directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/libpng'
2475 error cd ../opngreduc && \
2475 error make -f Makefile libopngreduc.a && \
2475 error cd ../optipng
2475 error make[2]: Entering directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/opngreduc'
2475 error gcc -c  -O2 -Wall -Wextra  -I../libpng -o opngreduc.o opngreduc.c
2475 error ar cru libopngreduc.a opngreduc.o
2475 error ranlib libopngreduc.a
2475 error make[2]: Leaving directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/opngreduc'
2475 error cd ../gifread && \
2475 error make -f Makefile libgifread.a && \
2475 error cd ../optipng
2475 error make[2]: Entering directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/gifread'
2475 error gcc -c  -O2 -Wall -Wextra -o gifread.o gifread.c
2475 error ar cru libgifread.a gifread.o
2475 error ranlib libgifread.a
2475 error make[2]: Leaving directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/gifread'
2475 error cd ../pnmio && \
2475 error make -f Makefile libpnmio.a && \
2475 error cd ../optipng
2475 error make[2]: Entering directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/pnmio'
2475 error gcc -c  -O2 -Wall -Wextra -o pnmin.o pnmin.c
2475 error gcc -c  -O2 -Wall -Wextra -o pnmout.o pnmout.c
2475 error gcc -c  -O2 -Wall -Wextra -o pnmutil.o pnmutil.c
2475 error ar cru libpnmio.a pnmin.o pnmout.o pnmutil.o
2475 error ranlib libpnmio.a
2475 error make[2]: Leaving directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/pnmio'
2475 error cd ../minitiff && \
2475 error make -f Makefile libminitiff.a && \
2475 error cd ../optipng
2475 error make[2]: Entering directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/minitiff'
2475 error gcc -c  -O2 -Wall -Wextra -o tiffread.o tiffread.c
2475 error gcc -c  -O2 -Wall -Wextra -o tiffutil.o tiffutil.c
2475 error ar cru libminitiff.a tiffread.o tiffutil.o
2475 error ranlib libminitiff.a
2475 error make[2]: Leaving directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/minitiff'
2475 error cd ../pngxtern && \
2475 error make -f Makefile libpngxtern.a && \
2475 error cd ../optipng
2475 error make[2]: Entering directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/pngxtern'
2475 error gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxread.o pngxread.c
2475 error gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrbmp.o pngxrbmp.c
2475 error gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrgif.o pngxrgif.c
2475 error gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrjpg.o pngxrjpg.c
2475 error gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrpnm.o pngxrpnm.c
2475 error gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrtif.o pngxrtif.c
2475 error gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxio.o pngxio.c
2475 error gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxmem.o pngxmem.c
2475 error gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxset.o pngxset.c
2475 error ar cru libpngxtern.a pngxread.o pngxrbmp.o pngxrgif.o pngxrjpg.o pngxrpnm.o pngxrtif.o pngxio.o pngxmem.o pngxset.o
2475 error ranlib libpngxtern.a
2475 error make[2]: Leaving directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/pngxtern'
2475 error gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o optipng.o optipng.c
2475 error gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o optim.o optim.c
2475 error gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o bitset.o bitset.c
2475 error gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o ioutil.o ioutil.c
2475 error gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o ratio.o ratio.c
2475 error gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o wildargs.o wildargs.c
2475 error gcc -s -o optipng optipng.o optim.o bitset.o ioutil.o ratio.o wildargs.o ../opngreduc/libopngreduc.a ../pngxtern/libpngxtern.a ../libpng/libpng.a  ../gifread/libgifread.a ../pnmio/libpnmio.a ../minitiff/libminitiff.a  -lz -lm
2475 error make[1]: Leaving directory '/tmp/3d2bcd4c-bafc-49fb-b3d6-4542384570dd/src/optipng'
2475 error
2475 error     at /home/user/chia-blockchain/chia-blockchain-gui/node_modules/bin-build/node_modules/execa/index.js:231:11
2475 error     at runMicrotasks (<anonymous>)
2475 error     at processTicksAndRejections (node:internal/process/task_queues:94:5)
2475 error     at async /home/user/chia-blockchain/chia-blockchain-gui/node_modules/optipng-bin/lib/install.js:18:4
2476 verbose exit 1
```

**Comment by hoffmang9** [comment]
That set of image libs will be going out in the next release.

Here is the workaround I created for the installers - https://github.com/Chia-Network/chia-blockchain/blob/v1.0.x/build_scripts/build_linux.sh#L54

**Comment by seeden** [comment]
already merged
