### ISSUE TITLE
Updating to 1.0.4 on Ubuntu gave me ModuleNotFoundError: No module named 'src.cmds.chia' error on chia init

### ISSUE THREAD

**Issue by mountriv99** [Chia-Network/chia-blockchain-gui#258]
(venv) e@E:~/chia-blockchain$ chia init
Traceback (most recent call last):
  File "/home/e/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/e/chia-blockchain/venv/bin/chia", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src.cmds.chia'

**Comment by hoffmang9** [comment]
The `chia-blockchain-gui` directory has a file keeping it from updating. Usually `package-lock.json`
