### ISSUE TITLE
GUI should not allow buckets >128 to be specified.

### ISSUE THREAD

**Issue by tjsr** [Chia-Network/chia-blockchain-gui#273]
The GUI permits the user to specify any number of buckets, however a value >128 is already caught by the application and an exception thrown if passed as an argument.

When trying to specify buckets > 128 in the Windows GUI, the plot will fail to start with the following exception:

Caught plotting error: Maximum buckets is 128
[19136] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 80, in <module>
  File "chia\cmds\chia.py", line 76, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 134, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

The GUI should not enable the user to specify a value which is going to cause the plot to fail to start.

**Comment by seeden** [comment]
Thanks :) nice catch. I will add this limit

**Comment by seeden** [comment]
The maximum value will change in the short run. I will add this limit after this change
