### ISSUE TITLE
[BUG] Installing GUI with install-gui.sh on Ubuntu 20.04 LTS - Cannot find module 'fuzzaldrin'

### ISSUE THREAD

**Issue by cmberlin** [Chia-Network/chia-blockchain-gui#291]
Trying to install using install-gui.sh on active venv throws error. Followed installation instructions for Ubuntu from wiki!

Ubuntu 20.04 LTS
Kernel version: 5.4.0-72-generic

Node via nvm:
info using npm@7.5.4
info using node@v14.12.0

npm log error:
```
verbose stack Error: command failed
verbose stack     at ChildProcess.<anonymous> (/home/.nvm/versions/node/v14.12.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
verbose stack     at ChildProcess.emit (events.js:314:20)
verbose stack     at maybeClose (internal/child_process.js:1047:16)
verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

Console error:
```
Installing on Ubuntu 20.04 LTS or newer: Using installed node.js version
Running git submodule update --init --recursive.

Running git submodule update.


up to date, audited 2026 packages in 3s

found 0 vulnerabilities

up to date, audited 2026 packages in 4s

found 0 vulnerabilities

> build
> npm run locale && npm run build:electron && npm run build:react


> locale
> lingui extract && lingui compile

internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module 'fuzzaldrin'
Require stack:
- /home/apps/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/api/utils.js
- /home/apps/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/lingui.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/apps/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/api/utils.js:22:19)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/apps/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/api/utils.js',
    '/home/apps/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/lingui.js'
  ]
}
```
Any idea?
Thx Carsten

**Comment by seeden** [comment]
Can you try to run "npm install --legacy-peer-deps" inside directory chia-blockchain-gui? and then run "npm run build" again?

**Comment by cmberlin** [comment]
Did a complete new install with the latest version today. When i try to install the gui it gets stuck while downloading the material-ui/icons package. I have to cancel. After that i run the install script again and all the packages seems to being downloaded but the following error occurs:

```
build
> npm run locale && npm run build:electron && npm run build:react


> locale
> lingui extract && lingui compile

sh: 1: lingui: not found
npm ERR! code 127
npm ERR! path /home/apps/chia-blockchain/chia-blockchain-gui
npm ERR! command failed
npm ERR! command sh -c lingui extract && lingui compile

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2021-04-22T11_56_08_213Z-debug.log
npm ERR! code 127
npm ERR! path /home/apps/chia-blockchain/chia-blockchain-gui
npm ERR! command failed
npm ERR! command sh -c npm run locale && npm run build:electron && npm run build:react
```
When i run npm install --legacy-peer-deps everthing seems to be ok
```
npm install --legacy-peer-deps

up to date, audited 2026 packages in 3s

found 0 vulnerabilities
```
Running npm build throws same error as described above

**Comment by seeden** [comment]
Thank you. Can you verify if this path exists? chia-blockchain-gui/node_modules/.bin/lingui

**Comment by cmberlin** [comment]
I figured out that installing packages and building with npm 6.14.4 works as expected. Running the gui with node 14.12.0 seems to be working also. Therefore i cannot answer your question above anymore.

**Comment by cmberlin** [comment]
Not sure if it makes sense to close this issue because installing and building with npm 7.5.4 still does not work!
