### ISSUE TITLE
[BUG] GUI Crash after Plotting delete

### ISSUE THREAD

**Issue by lucalas** [Chia-Network/chia-blockchain-gui#359]
I created 2 plotting "Plot in parallel" (first with 3 plots delayed of 180 minutes, second with 2 plots delayed of 180 minutes) and after some minutes I had to delete them.
When I stopped the second groups of plots GUI Crashes remaining in reconnecting state "Connecting to wallet", i tried to close but he didn't so I had to force kill. 

Everything I found in debug.log is this error in the crash instant:
2021-05-06T22:08:14.517 harvester chia.plotting.plot_tools: INFO     Searching directories ['F:\\plot\\final', 'H:\\plot\\final', 'E:\\plot\\final']
2021-05-06T22:08:14.548 harvester harvester               : INFO     got signal 21
2021-05-06T22:08:14.548 harvester harvester               : INFO     Cancelling reconnect task
2021-05-06T22:08:14.548 harvester harvester               : INFO     Closing connections
2021-05-06T22:08:14.548 harvester harvester               : INFO     Calling service stop callback
2021-05-06T22:08:14.548 harvester harvester               : INFO     Closing RPC server
2021-05-06T22:08:14.595 farmer farmer                     : INFO     got signal 21
2021-05-06T22:08:14.595 full_node full_node               : INFO     got signal 21
2021-05-06T22:08:14.595 full_node full_node               : INFO     Cancelling reconnect task
2021-05-06T22:08:14.595 full_node full_node               : INFO     Closing connections
2021-05-06T22:08:14.595 full_node full_node               : INFO     Calling service stop callback
2021-05-06T22:08:14.595 full_node full_node               : INFO     Closing RPC server
2021-05-06T22:08:14.595 full_node full_node               : INFO     Waiting for socket to be closed (if opened)
2021-05-06T22:08:14.595 full_node full_node               : INFO     Waiting for ChiaServer to be closed
2021-05-06T22:08:14.595 full_node chia.full_node.full_node: ERROR    Exception in create outbound connections: 
2021-05-06T22:08:14.595 full_node chia.full_node.full_node: ERROR    Traceback: Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 325, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

- OS: Windows 10 Pro
- OS Version/Flavor: 19042.928
- CPU: Intel I5 4670K

**Comment by modmoto** [comment]
ahh, good to know. Experienced the same thing.

**Comment by keithsavage777** [comment]
help

**Comment by keithsavage777** [comment]
same here on both PCs

**Comment by Habag111** [comment]
I'm experiencing the same behavior on windows 10.

**Comment by racabu** [comment]
I experienced the same issue deleting a plot from the queue
