### ISSUE TITLE
Installing GUI error - error Failed at the chia-blockchain@ build:react script.

### ISSUE THREAD

**Issue by chriswalker01** [Chia-Network/chia-blockchain-gui#369]
Hi,

I'm getting the following error when trying to install the gui on Mint 20.1 (Ubuntu 20.04).

error Failed at the chia-blockchain@ build:react script.

I've had a look at other issues and found one similar where someone was installing it on an AL2 server. Mine is a VM running on kvm, but I'm running the install script via the console, so it does have a graphical interface.

`$ lspci | grep VGA
00:02.0 VGA compatible controller: Cirrus Logic GD 5446`

Can anyone point me in the right direction and tell me what's wrong?

The full log is below.
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:react' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild:react', 'build:react', 'postbuild:react' ]
5 info lifecycle chia-blockchain@~prebuild:react: chia-blockchain@
6 info lifecycle chia-blockchain@~build:react: chia-blockchain@
7 verbose lifecycle chia-blockchain@~build:react: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~build:react: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/chris/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/chris/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/home/chris/chia-blockchain/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle chia-blockchain@~build:react: CWD: /home/chris/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~build:react: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=production webpack --config ./webpack.react.babel.ts' ]
11 silly lifecycle chia-blockchain@~build:react: Returned: code: 1  signal: null
12 info lifecycle chia-blockchain@~build:react: Failed to exec build:react script
13 verbose stack Error: chia-blockchain@ build:react: `cross-env NODE_ENV=production webpack --config ./webpack.react.babel.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid chia-blockchain@
15 verbose cwd /home/chris/chia-blockchain/chia-blockchain-gui
16 verbose Linux 5.4.0-58-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:react"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error chia-blockchain@ build:react: `cross-env NODE_ENV=production webpack --config ./webpack.react.babel.ts`
22 error Exit status 1
23 error Failed at the chia-blockchain@ build:react script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by chriswalker01** [comment]
All good....I used the new experimential installer and it worked.
