### ISSUE TITLE
error 32k 

### ISSUE THREAD

**Issue by mgxmurat** [Chia-Network/chia-blockchain-gui#390]
good afternoon gave this error when the plot is 33% and it stayed that way what should i do     

tarting phase 3/4: Compression from tmp files into "C:\\32k16\\plot-k32-2021-05-14-20-59-8840c92962088fab5c2c9cb7d1144c9ee60af5185117b273d6dbacc89b3a9591.plot.2.tmp" ... Sat May 15 02:25:49 2021
Compressing tables 1 and 2
Caught plotting error: bad allocation
[12676] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation
