### ISSUE TITLE
Cannot join pool 

### ISSUE THREAD

**Issue by zhq7857** [Chia-Network/chia-blockchain-gui#504]
The node and wallet have been synchronized, and then can‘t join the pool or change pool. Whether it is reinstalled or waiting, the state of the pool remains unchanged and cannot be deleted

the log ：
2021-07-25T04:23:18.872 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 203, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 626, in get_transaction
ValueError: Transaction 0xbc0f0e0a59aaceec766bf5b28692650ea8b92afc675074f688b651410f7222cb not found

2021-07-25T04:23:19.869 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 203, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 626, in get_transaction
ValueError: Transaction 0xbc0f0e0a59aaceec766bf5b28692650ea8b92afc675074f688b651410f7222cb not found

2021-07-25T04:23:20.873 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 203, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 626, in get_transaction
ValueError: Transaction 0xbc0f0e0a59aaceec766bf5b28692650ea8b92afc675074f688b651410f7222cb not found
![2](https://user-images.githubusercontent.com/37865616/126881038-23ad1ae7-80ca-41d7-8c9c-c31de4ab80ce.jpg)

![1](https://user-images.githubusercontent.com/37865616/126881020-062f1fde-0b77-4a00-9b39-c1b7fb94bae9.jpg)

**Comment by seeden** [comment]
Thank you for your report. I am working on this issue
