### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by mattn08** [Chia-Network/chia-blockchain-gui#712]
### What happened?

Opened the GUI (ubuntu) to my remote (pi4) chia node, clicked on the key account and immediately it goes to this crash screen. Happens every time, 1.3.4 is also broken but goes blank rather than giving a message.

### Version

1.3.5-dev88

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'find')

URL
#/dashboard/wallets/1

Stacktrace
at webpack://@chia/wallets/dist/esm.js:3741:29 strayCats.find(function
at webpack://@chia/wallets/dist/esm.js:3798:14 _toConsumableArray(nonAddedKnownCats.map(function
at webpack://@chia/wallets/dist/esm.js:3790:46 _toConsumableArray(nonAddedKnownCats.map(function
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:168:376 $h
at webpack://@chia/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia/wallets/dist/esm.js:3747:13 useMemo(function
at webpack://@chia/wallets/dist/esm.js:4294:39 WalletsManageTokens
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
```

**Comment by seeden** [comment]
Fixed with https://github.com/Chia-Network/chia-blockchain-gui/pull/713

**Comment by seeden** [comment]
Merged
