### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'dark')

### ISSUE THREAD

**Issue by cdgm01** [Chia-Network/chia-blockchain-gui#714]
### What happened?

i cant import my mnemonics words

### Version

1.3.594

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'dark')

URL


Stacktrace
at webpack://@chia/gui/node_modules/@mui/material/Button/Button.js:101:53 dark
at webpack://@chia/gui/node_modules/@mui/system/esm/createStyled.js:189:17 Array(numOfCustomFnsApplied).fill
at webpack://@chia/src/utils/flatten.js:68:21 isStatelessFunction
at webpack://@chia/src/models/ComponentStyle.js:91:28 phash
at webpack://@chia/src/models/StyledComponent.js:87:21 useInjectedStyle<T>
at webpack://@chia/src/models/StyledComponent.js:126:4 componentStyle
at webpack://@chia/src/models/StyledComponent.js:245:27 forwardRef
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:176:259 useOpaqueIdentifier
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:271:399 d=b.pendingProps;e=b.memoizedState;e=null!==e?e.element:null;yg(a,b);Cg(b,d,null,c);d=b.memoizedState.element;if(d===e)sh(),b=hi(a,b,c);else{e=b.stateNode;if(f=e.hydrate)kh=rf(b.stateNode.containerInfo.firstChild),jh=b,f=lh=!0;if
```

**Comment by seeden** [comment]
duplicate of https://github.com/Chia-Network/chia-blockchain-gui/issues/738
