### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'syncing')

### ISSUE THREAD

**Issue by mmitech** [Chia-Network/chia-blockchain-gui#724]
### What happened?

[BUG] Cannot read properties of undefined (reading 'syncing')

### Version

1.3.577

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'syncing')

URL
#/dashboard/wallets/1

Stacktrace
at webpack://@chia/wallets/dist/esm.js:395:53 syncing
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:342 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
```

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/749/files
