### ISSUE TITLE
[BUG] Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by sejrej** [Chia-Network/chia-blockchain-gui#737]
### What happened?

I have been having trouble in the last 2 weeks getting the GUI to see my hard drives.  I uninstalled and then reinstalled to the latest version released and when I go to add plot folders it gave me this error 

### Version

13.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of null (reading 'map')

URL
#/dashboard/farm

Stacktrace
at webpack://@chia/gui/src/components/plot/PlotAddDirectoryDialog.tsx:95:25 map
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:342 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
```

**Comment by seeden** [comment]
Thank you. I will take care of it

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/749/files
