### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by Taka-Tim** [Chia-Network/chia-blockchain-gui#762]
### What happened?

application was broken whe I click to "wallet" button

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'filter')

URL
#/dashboard/wallets/1

Stacktrace
at webpack://@chia/wallets/dist/esm.js:3754:30 wallets.filter(function
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:168:376 $h
at webpack://@chia/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia/wallets/dist/esm.js:3747:13 useMemo(function
at webpack://@chia/wallets/dist/esm.js:4296:39 WalletsManageTokens
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:342 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
```

**Comment by seeden** [comment]
This issue was already fixed. It will work in the next release
