### ISSUE TITLE
[BUG] Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by dmc1648** [Chia-Network/chia-blockchain-gui#799]
### What happened?

Just installing from a Win11 Pro crash (All data lost).  Trying to get back up and running and I got this Error from my add plots dir.

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Something went wrong
Error: Cannot read properties of null (reading 'map')

at webpack://@chia/gui/src/components/plot/PlotAddDirectoryDialog.tsx:95:25 map
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:342 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
```

**Comment by seeden** [comment]
This issue was fixed in the latest 1.4 version. Please upgrade your version
