### ISSUE TITLE
[Bug] Repeated timeout when trying to send XCH 

### ISSUE THREAD

**Issue by wv-krmkz** [Chia-Network/chia-blockchain-gui#827]
### What happened?

Attempting to send a couple XCH from one wallet to another on Win10 Chia 1.4 and getting repeated timeouts on the Tx. 

Never had trouble with this on past versions. Any suggestions? Thanks.

### Version

1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
2022-07-02T16:03:37.749 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 229, in safe_handle
  File "chia\rpc\rpc_server.py", line 220, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 838, in send_transaction
  File "chia\wallet\wallet.py", line 432, in generate_signed_transaction
  File "chia\wallet\wallet.py", line 315, in _generate_unsigned_transaction
  File "chia\wallet\wallet.py", line 267, in select_coins
  File "chia\wallet\coin_selection.py", line 90, in select_coins
  File "chia\wallet\coin_selection.py", line 119, in select_smallest_coin_over_target
ValueError: Unable to select coins for this transaction. Try sending a smaller amount
```

**Comment by wv-krmkz** [comment]
Reduced the amount to 1 XCH and same result. The spendable balance in the wallet is more than these amounts.

**Comment by wv-krmkz** [comment]
I reduced the amount even further and same result.
