### ISSUE TITLE
[BUG] Cannot create new private key

### ISSUE THREAD

**Issue by charbob** [Chia-Network/chia-blockchain-gui#845]
### What happened?

Fresh install of Chia for Windows 1.4.0, using Windows 10.

I launched the application, and I already have a wallet on my system (that is part of a farming group I am a part of). I click "Create a new private key" and this error happens. I am trying to make a second key for myself that is separate from the existing key for my group.

### Version

1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'dark')

URL


Stacktrace
at webpack://@chia/gui/node_modules/@mui/material/Button/Button.js:101:53 dark
at webpack://@chia/gui/node_modules/@mui/system/esm/createStyled.js:191:17 Array(numOfCustomFnsApplied).fill
at webpack://@chia/src/utils/flatten.js:68:21 isStatelessFunction
at webpack://@chia/src/models/ComponentStyle.js:91:28 phash
at webpack://@chia/src/models/StyledComponent.js:87:21 useInjectedStyle<T>
at webpack://@chia/src/models/StyledComponent.js:126:4 componentStyle
at webpack://@chia/src/models/StyledComponent.js:245:27 forwardRef
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:176:259 useOpaqueIdentifier
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:271:399 d=b.pendingProps;e=b.memoizedState;e=null!==e?e.element:null;yg(a,b);Cg(b,d,null,c);d=b.memoizedState.element;if(d===e)sh(),b=hi(a,b,c);else{e=b.stateNode;if(f=e.hydrate)kh=rf(b.stateNode.containerInfo.firstChild),jh=b,f=lh=!0;if
```

**Comment by paninaro** [comment]
Thanks for the report. Can you try deleting the contents in `%APPDATA\Chia Blockchain` (should be equivalent to `%USERHOME%\AppData\Roaming\Chia Blockchain`) and restarting Chia?
