### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'className')

### ISSUE THREAD

**Issue by rwal127** [Chia-Network/chia-blockchain-gui#851]
### What happened?

I click show offer details button and get "Something went wrong" error.

### Version

1.5.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'className')

URL
#/dashboard/offers/view

Stacktrace
at webpack://@chia/gui/node_modules/@mui/material/Tooltip/Tooltip.js:507:52 popperRef.current.update
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:176:259 useOpaqueIdentifier
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:271:399 d=b.pendingProps;e=b.memoizedState;e=null!==e?e.element:null;yg(a,b);Cg(b,d,null,c);d=b.memoizedState.element;if(d===e)sh(),b=hi(a,b,c);else{e=b.stateNode;if(f=e.hydrate)kh=rf(b.stateNode.containerInfo.firstChild),jh=b,f=lh=!0;if
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
```

**Comment by seeden** [comment]
fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/855
