### ISSUE TITLE
GUI NFT DID assignment crash

### ISSUE THREAD

**Issue by CommanderMoto** [Chia-Network/chia-blockchain-gui#862]
### What happened?

Attempted to transfer an NFT to my profile. Something went wrong.
Windows 11.

### Version

1.5.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'map')

URL
#/dashboard/nfts

Stacktrace
at webpack://@chia/gui/src/components/nfts/NFTMoveToProfileDialog.tsx:220:17 map
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:172:114 useLayoutEffect
at webpack://@chia/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia/gui/src/components/nfts/NFTMoveToProfileDialog.tsx:211:36 useMemo
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:267:459 b?b.sibling:null}I
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
```

**Comment by CommanderMoto** [comment]
Aaaaaaand on app restart, it looks like my keys are all gone.
So I stopped the app again, and notice there's still start_full_node and start_wallet processes hanging out in my perfmon.
This is looking pretty bj0rken. I'm gonna give it another couple of hours for those processes to finish, lest I corrupt my DB unnecessarily, but a reboot seems likely in the near future.

**Comment by CommanderMoto** [comment]
(this bug duplicates #841)

**Comment by CommanderMoto** [comment]
okay ... I do not know Windows process management well enough to deal with all these start_* processes which appear to have lost their controlling chia.exe (while still writing a sustained 6-7MB/s to disk) - guess it's time for a reboot.
