### ISSUE TITLE
Invalid address on offer file | [BUG] Cannot read properties of undefined (reading 'className')

### ISSUE THREAD

**Issue by SemnoSao** [Chia-Network/chia-blockchain-gui#864]
### What happened?

I have accepted an offer from a invalid address. After accepting it showed here:
![image](https://user-images.githubusercontent.com/16153554/182262836-e0f535e7-87a8-4d09-becf-5af4af6d3d1b.png)

I tried to cancel the offer but still have a pending balance. If I try to click on the address I get this error that redirected me to this page.

Did I lose my chia? Can I do anything more to help so it doesn't happen again?

### Version

1.5.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'className')

URL
#/dashboard/offers/view

Stacktrace
at webpack://@chia/gui/node_modules/@mui/material/Tooltip/Tooltip.js:507:52 popperRef.current.update
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:176:259 useOpaqueIdentifier
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:271:399 d=b.pendingProps;e=b.memoizedState;e=null!==e?e.element:null;yg(a,b);Cg(b,d,null,c);d=b.memoizedState.element;if(d===e)sh(),b=hi(a,b,c);else{e=b.stateNode;if(f=e.hydrate)kh=rf(b.stateNode.containerInfo.firstChild),jh=b,f=lh=!0;if
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:277 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:137 Pj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:243:162 Lj
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:123:114 jg
at webpack://@chia/gui/node_modules/scheduler/cjs/scheduler.production.min.js:18:342 unstable_next
```

**Comment by SemnoSao** [comment]
in the end I have really received the NFT. Is it fake? Sapcescan show it as verified. Should I check anything more?
