### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by CityIllusion** [Chia-Network/chia-blockchain-gui#942]
### What happened?

GUI crashed

### Version

1.5.1510

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output or stacktrace

```shell
Cannot read properties of undefined (reading 'id')

URL
#/dashboard/nfts

Stacktrace
at webpack://@chia/gui/src/components/nfts/NFTProfileDropdown.tsx:84:31 id
at webpack://@chia/gui/src/components/nfts/NFTProfileDropdown.tsx:82:45 filter
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:168:376 $h
at webpack://@chia/gui/node_modules/react/cjs/react.production.min.js:23:112 useLayoutEffect
at webpack://@chia/gui/src/components/nfts/NFTProfileDropdown.tsx:77:30 useMemo
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:157:136 Ch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:180:153 oi
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:269:342 a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch
at webpack://@chia/gui/node_modules/react-dom/cjs/react-dom.production.min.js:250:346 Pj
```

**Comment by paninaro** [comment]
Thanks for reporting the issue. This has been fixed in `main` and is included in the next release.

Issue used for tracking the issue: https://github.com/Chia-Network/chia-blockchain/issues/12920
Fix: https://github.com/Chia-Network/chia-blockchain-gui/commit/8d5bd4f3e0a94b0ea5f4c31bc279c7c883ff9948
